version: "3.9"

services:
  backend:
    build: ./backend
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    restart: always
    env_file: .env
    environment:
      BACKEND_URL: http://127.0.0.1:8000
    network_mode: host
    depends_on:
      - backend

  bot:
    build: ./backend
    restart: always
    env_file: .env
    command: python -m bot.bot
    working_dir: /app
    network_mode: host
    depends_on:
      - backend
    environment:
      API_URL: http://127.0.0.1:8000
